POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@user.com",
    "password": "admin",
    "role": "ADMIN"
}

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwicm9sZSI6IkFETUlOIiwic3ViIjoiY21nZjUwbjV6MDAwMmN2cTFhZWlyZjJ0NiIsImlhdCI6MTc1OTc1ODM0NywiZXhwIjoxNzU5NzY1NTQ3fQ.Baz9019W0K7pu2OeRGSETnByHb5IE9jEw696aEBUqw4

###

GET http://localhost:3000/users/cmgf50n5z0002cvq1aeirf2t6

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}